exclude: [".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor", "_template.md", "_new_post.rb"]
name: Ohithere (it's Owen)
markdown: kramdown
permalink: /:categories/:title
url: https://owenwang.com
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path:            "embed/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "learningnight/*"
    values:
      sitemap:         false