exclude: [".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gem    file", "Gemfile.lock", "Procfile", "vendor", "_template.md", "_new_post.rb"]
name: Ohithere (it's Owen)
markdown: rdiscount
permalink: /blog/:title
